version: '2'

services:

  mysql:
    image: docker.io/bitnami/mysql
    ports:
      - "3306:3306"

    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp

    networks:
      - tribunal-network

  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:gmssOoTYqst9dKU1jMiPt7RIgFfU0iFbWSaN0wSWrFU=
      - APP_DEBUG=true
      - APP_URL=http://localhost

      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=tribunaldecuentas
      - DB_USERNAME=root
      - DB_PASSWORD=

      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120

      - MEMCACHED_HOST=127.0.0.1

      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379

      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_FROM_NAME="${APP_NAME}"

      - AWS_DEFAULT_REGION=us-east-1


      - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
    volumes:
      - '.:/app'
    depends_on:
      - mysql
    networks:
      - tribunal-network

#Docker Networks
networks:
  tribunal-network:
    driver: bridge